# Site settings
title: Green Sibshops
email: contactus@greensibshops.org
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://www.greensibshops.org" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
